version: "3.9"

services:
  api:
    image: docker.jala.pro/docker-training/backend:calebespinoza
    container_name: api
    networks:
      - jala-network
    volumes:
      - backend-data:/add/data
    ports:
      - "5000:5000"

  fe:
    image: docker.jala.pro/docker-training/frontend:calebespinoza
    container_name: fe
    networks:
      - jala-network
    volumes:
      - frontend-data:/add/data
    ports:
      - "3000:80"

networks:
  jala-network:
    external: true

volumes:
  backend-data:
  frontend-data:
